from typing import Callable, Optional, Tuple

NFULNL_COPY_NONE: int
NFULNL_COPY_META: int
NFULNL_COPY_PACKET: int

NFULNL_CFG_F_SEQ: int
NFULNL_CFG_F_SEQ_GLOBAL: int

class NetfilterLogData:
    """Wrapper for (struct nflog_data *)."""

    def get_hwtype(self) -> int: ...
    def get_msg_packet_hwhdr(self) -> str: ...
    def get_packet_hw(self) -> Optional[str]: ...
    def get_nfmark(self) -> int: ...
    def get_timestamp(self) -> Tuple[int, int]: ...
    def get_indev(self) -> int: ...
    def get_physindev(self) -> int: ...
    def get_outdev(self) -> int: ...
    def get_physoutdev(self) -> int: ...
    def get_payload(self) -> str: ...
    def get_prefix(self) -> str: ...
    def get_uid(self) -> int: ...
    def get_gid(self) -> int: ...
    def get_seq(self) -> int: ...
    def get_seq_global(self) -> int: ...

class NetfilterLogGroupHandle:
    """Wrapper for (struct nflog_g_handle *)."""

    def set_callback(self, callback: Callable[[NetfilterLogData], object]) -> None: ...
    def set_mode(self, mode: int, range: int) -> None: ...
    def set_timeout(self, timeout: int) -> None: ...
    def set_qthresh(self, qthresh: int) -> None: ...
    def set_nlbufsiz(self, nlbufsiz: int) -> None: ...
    def set_flags(self, flags: int) -> None: ...
    def unbind(self) -> None: ...

class NetfilterLogHandle:
    """Wrapper for (struct nflog_handle *)."""

    def bind_pf(self, pf: int) -> None: ...
    def unbind_pf(self, pf: int) -> None: ...
    def bind_group(self, num: int) -> NetfilterLogGroupHandle: ...
    def handle_packet(self, data: str) -> None: ...
    def fd(self) -> int: ...
    def close(self) -> None: ...

def open() -> NetfilterLogHandle: ...
